### ISSUE TITLE
Items that are not ImageViews cause disorted photos

### ISSUE THREAD

**Issue by eshkoliGilad** [500px/greedo-layout-for-android#10]
When I'm trying to wrap ImageView with, say, RelativeLayout, the items becomes disorted.

Why is that ? I want to add views on top of imageView so I need a container but that makes thing look very bad.

Any idea why ?

**Comment by eshkoliGilad** [comment]
Never mind, got that working.

**Comment by tbruyelle** [comment]
@eshkoliGilad I have the same issue, when my ImageView is wrapped with another layout it is disorted. How did you fix that please ?

**Comment by eshkoliGilad** [comment]
I've just made sizeForChildAtPosition() method of GreedoLayoutManager static and I call it in OnBind in the adapter:

        holder.mImageView.getLayoutParams().width = GreedoLayoutManager.sizeForChildAtPosition(position).getWidth();
        holder.mImageView.getLayoutParams().height = GreedoLayoutManager.sizeForChildAtPosition(position).getHeight();

**Comment by tbruyelle** [comment]
@eshkoliGilad Ok so you had to update the library code. In that case your issue is still valid. I opened a similar one here #16

**Comment by The-RobinHood** [comment]
@eshkoliGilad  It will helpful if you share  _GreedoLayoutManager_ class, I'm also struggling to over come this issue.
thanks

**Comment by eshkoliGilad** [comment]
@The-RobinHood 

The only thing I did for setting sizeForChildAtPosition() static and then in you onBind() function just calling:

holder.mImageView.getLayoutParams().width = GreedoLayoutManager.sizeForChildAtPosition(position).getWidth();
    holder.mImageView.getLayoutParams().height = GreedoLayoutManager.sizeForChildAtPosition(position).getHeight();

You may consider using this on your main container also if this doesn't help you.

I know it is not the perfect solution, but it was the quickest one.

**Comment by The-RobinHood** [comment]
@eshkoliGilad  can you share your _GreedoLayoutManager_ class, if you don't mind?

**Comment by The-RobinHood** [comment]
@eshkoliGilad  hey, it will really helpful to me if you share your _GreedoLayoutManager_ class, I'm stuck with this issue for a week. thanks

**Comment by abeemukthees** [comment]
@The-RobinHood can u please tell us, how u solved the issue ? #21

**Comment by olik79** [comment]
Just changing the method to static will not work, as it accesses instance variables which of course aren't valid in a static context.

What I did instead was to give the GreedoLayoutSizeCalculator (which can be retrieved by GreedoLayoutManager#getSizeCalculator()) to my adapter. I just added a member variable and a setter. After that you can just do the following within your onBindViewHolder(...) method:

        Size imageViewSize = mSizeCalculator.sizeForChildAtPosition(position);
        holder.itemView.getLayoutParams().width = imageViewSize.getWidth();
        holder.itemView.getLayoutParams().height = imageViewSize.getHeight();

I still don't really like this because I feel like it doesn't really match the concept of adapters and layout managers, but if I remember correctly I didn't have to change any library code.
