### ISSUE TITLE
Sample implement in Fragment extension

### ISSUE THREAD

**Issue by Ayysir** [500px/greedo-layout-for-android#11]
Any way to add a class in sample app to display how to implement in a fragment?

recyclerview is called in Mainactivity extended to AppCompatActivity
can you post example of it extended to Fragment?

**Comment by JVillella** [comment]
Hey @Ayysir it would be nearly identical. There's nothing unique about its usage with an activity vs a fragment. The only part that would change is creating a fragment and moving the applicable sample code into it, and attaching the fragment to `MainActivity`. Hope that helps!

**Comment by Ayysir** [comment]
Sorry @JVillella , I am calling the adapter in a class that extends to fragment, it isnt  called in the mainactivity. 

there is  error on "this" in 
`MyRecyclerAdapter recyclerAdapter = new MyRecyclerAdapter(this);`

which then wants it to make a constructor but then errors
`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ayysir.pixl.debug/com.ayysir.pixl.activities.PixlActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.RecyclerView.setLayoutManager(android.support.v7.widget.RecyclerView$LayoutManager)' on a null object reference`

**Comment by alashow** [comment]
`this`  is `Activity` object instance, which is extends `Context` (it is god object in Android), and adapters constructor's parameter is `Context`.

From fragment, you can call `getActivity()` to get host activity:
```MyRecyclerAdapter recyclerAdapter = new MyRecyclerAdapter(getActivity());```

**Comment by Ayysir** [comment]
@alashow doesnt work since my adapter already calls Activity:
`import android.app.Activity;
import android.content.Intent;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;

import com.ayysir.pixl.R;
import com.ayysir.pixl.WallsUtil.Palette;
import com.ayysir.pixl.activities.WpDetailActivity;
import com.ayysir.pixl.models.Wallpaper;
import com.fivehundredpx.greedolayout.GreedoLayoutSizeCalculator;
import com.squareup.picasso.Picasso;

import java.util.List;

public class WpRecyclerViewAdapter
        extends RecyclerView.Adapter<WpRecyclerViewAdapter.WallsViewHolder> implements GreedoLayoutSizeCalculator.SizeCalculatorDelegate {

    private Activity mActivity;
    private List<Wallpaper> mWallpaperList;

    @Override
    public double aspectRatioForIndex(int i) {
        return 0;
    }


    public static class WallsViewHolder extends RecyclerView.ViewHolder {
        public WallsViewHolder(View view) {
            super(view);
        }
    }

    public WpRecyclerViewAdapter(Activity activity, List<Wallpaper> wallpaperList) {
        super();
        mActivity = activity;
        mWallpaperList = wallpaperList;
    }

    @Override
    public WallsViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View view = LayoutInflater.from(parent.getContext())
                .inflate(R.layout.wallpaper_item, parent, false);
        return new WallsViewHolder(view);
    }

    @Override
    public void onBindViewHolder(WallsViewHolder holder, int position) {
        Wallpaper mWallpaper = mWallpaperList.get(position);
        final String mWallpaperUrl = mWallpaper.getUrl();
        ImageView mWallImageView = (ImageView) holder.itemView;

        Picasso.with(mActivity)
                .load(mWallpaperUrl)
                .fit()
                .centerInside()
                .transform(Palette.instance())
                .into(mWallImageView);

        // TODO: Add color ripple
        /* Drawable mDrawable = holder.mWallImageView.getDrawable();
        RippleDrawable rippledImage =
        new RippleDrawable(ColorStateList.valueOf(color)), mDrawable, null);
        holder.mWallImageView.setImageDrawable(rippledImage);*/

        mWallImageView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent = new Intent(mActivity, WpDetailActivity.class);
                intent.putExtra("wall", mWallpaperUrl);
                mActivity.startActivity(intent);
            }
        });
    }

    @Override
    public int getItemCount() {
        return mWallpaperList.size();
    }
}`

**Comment by alashow** [comment]
Actually, your exception not related to adapter. It says that you recyclerView is null, and you trying to set layout manager to null object.

**Comment by Ayysir** [comment]
@alashow  thats when i made a empty constructor. Since my Adapter has a contructor already, how can i call it to the fragment class?
