### ISSUE TITLE
Problem with saving the state of recyclerView

### ISSUE THREAD

**Issue by Pantkowsky** [500px/greedo-layout-for-android#31]
Hey guys

I have a problemwith saving the state of Recycler View using Greedo Layout Manager. I get this exception when calling:

`recyclerView.scrollToPosition(index);`

in onResume()

`03-06 12:35:55.287 20863-20863/com.artland E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.artland, PID: 20863
                                                             java.lang.RuntimeException: Invalid content width. Did you forget to set it?
                                                                 at com.fivehundredpx.greedolayout.GreedoLayoutSizeCalculator.computeChildSizesUpToPosition(GreedoLayoutSizeCalculator.java:101)
                                                                 at com.fivehundredpx.greedolayout.GreedoLayoutSizeCalculator.getRowForChildPosition(GreedoLayoutSizeCalculator.java:79)
                                                                 at com.fivehundredpx.greedolayout.GreedoLayoutManager.rowForChildPosition(GreedoLayoutManager.java:278)
                                                                 at com.fivehundredpx.greedolayout.GreedoLayoutManager.scrollToPosition(GreedoLayoutManager.java:306)
`

Any idea on how to fix it? Weird thing is, that both setContentWidth() and setMaxRowHeight() are public void methods, but I can only use setMaxRowHeight() when configuring the GreedoLayoutManager. setContentWidth() is not even visible as a useable method. 

Would highly appreciate any help! @mck182

**Comment by Pantkowsky** [comment]
Could somebody from 500px, who was creating the GreedoLayout for android, please comment on this issue? It is quite urgent for me and would highly appreciate any help with this problem. @JVillella @mck182

**Comment by mck182** [comment]
Hey there,

it took a while to get to this but we've now fixed
the crash, feel free to reopen this ticket if it didn't
resolve this issue for you.

Martin,
500px

**Comment by Pantkowsky** [comment]
Thanks ! I hope it is going to work now. However, is the library version still 1.0.0 ??

**Comment by Pantkowsky** [comment]
Hey @mck182 !

I've checked out the fixes you guys made to solving the problem with saving the state of GreedoManager. It does work in fact, however there is one thing that bothers me a lot, I wonder if it only happens for me or is a general issue:

1) open a fragment hosting a list of images with greedoManger
2) click on any to take you to another view displaying the full image
3) go back and see the position of the layout as you left it

Great, everything works as it was supposed to... however, the moment you scroll up (a fast scroll, like you would do to quickly get back to the top), the content is lost. Suddenly all the images disappear, although the presence of recyclerView is still there (you can see on the screen that it responds to scroll gestures). Only going to another fragment/activity and back resets the list of images. 

I also cant help but notice, that the app stutters a lot when it enters the process of restoring the state of GreedoManager. There is a huge hiccup (a slight screen freeze + FPS drop)

Do you reckon its something on my end of implementation (or maybe the phone) ? Or is it a general issue?

**Comment by mck182** [comment]
New version of the library is up - `1.1.0`, enjoy!

As for your issues, I've seen the disappearance
happen couple times, but I've never really had
a chance to investigate that.

Can you reliably reproduce that problem? Would
you be able to produce a minimal reproducible
code? Ie. a tiniest possible app that can reproduce
this? I could then investigate.

As for slowness, we haven't really seen that
so can't comment on that.

Cheers,
Martin from 500px
