### ISSUE TITLE
REQUEST: make sizeForChildAtPosition() public

### ISSUE THREAD

**Issue by Pantkowsky** [500px/greedo-layout-for-android#35]
![image](https://cloud.githubusercontent.com/assets/9194725/25809652/f5c3826c-340d-11e7-99e7-73dcb9d620df.png)

Could you make this method public? I need to calculate the sizes for each item in onBindViewHolder() but I can't call this method

**Comment by mck182** [comment]
Hi,

`sizeForChildAtPosition` in `GreedoLayoutSizeCalculator`
is already public.

https://github.com/500px/greedo-layout-for-android/blob/master/greedo-layout/src/main/java/com/fivehundredpx/greedolayout/GreedoLayoutSizeCalculator.java#L66

Cheers,
Martin from 500px

**Comment by Pantkowsky** [comment]
Hey @mck182 !

Thanks for the answer! I must be doing something wrong then. Adding these lines:

```
repositories {
	maven { url 'https://github.com/500px/greedo-layout-for-android/raw/master/releases/' }
}

dependencies {
	compile 'com.fivehundredpx:greedo-layout:1.0.0'
}
```

to the gradle build provide me with the version of the library where this method is not public (setFixedHeight() is neither), as well as recent changes where the scrollToPosition() (from my previous issue on how to save the state of GreedoManager) are not apparent. According to the README, these are the lines which should be included in the Gradle. Am I doing something wrong ? 

Thanks for your help!

**Comment by mck182** [comment]
Right, we need to release a new version.

In the meantime, you can use jitpack.io
and just use the github repo directly.

I'll try to push the new version soon.

Cheers,
Martin from 500px

**Comment by Pantkowsky** [comment]
Thanks Martin! 
@mck182

**Comment by mck182** [comment]
Ok, new version is up, `1.1.0`.

Enjoy!
Martin from 500px
