### ISSUE TITLE
Implementing with Volley

### ISSUE THREAD

**Issue by ansyori28** [500px/greedo-layout-for-android#43]
Hello, can you make a tutorial on implementing GreedoLayout with Volley? thanks.

**Comment by mck182** [comment]
Hey there,

we'd be happy to host an example that uses Volley
but as we're not using Volley ourselves, we don't
have the knowledge or experience needed to provide
that ourselves.

If someone supplies the sample implementation, I'd
be more than happy to put it here for others to use.

Cheers,
Martin
