### ISSUE TITLE
support for endless scrolling

### ISSUE THREAD

**Issue by vipulasri** [500px/greedo-layout-for-android#45]
There should be a class or code for implementing endless scrolling in this kind of layout manager

**Comment by shagylyjov** [comment]
See #4 and #12

**Comment by alashow** [comment]
See #4 and #12

**Comment by mck182** [comment]
That would be the responsibility of the RecyclerView
and your Fragment/Activity; the layout manager should
not be involved with that. The solution posted in #4 is
a good example of how to achieve that.
