### ISSUE TITLE
Is there a LinearLayout version?

### ISSUE THREAD

**Issue by AngleV** [500px/greedo-layout-for-android#7]
I am building an app and i need a custom LinearLayout Manager to support items with different heights.
In fact the app fetches images from a server with different aspect ratios so each item must have the equivalent height. Server returns the aspect ratios for each image so i know them all ready.

Is it possible to tweak the greedolayout some how to achieve the desired result ?

**Comment by JVillella** [comment]
The LinearLayoutManager can do this using `setAutoMeasureEnabled(...)`. Please see http://android-developers.blogspot.ca/2016/02/android-support-library-232.html. This feature came out last week.

**Comment by eshkoliGilad** [comment]
I'm also interested in building a FlowLayout-kind LayoutManager and it looks actually as something that I can use.

I'm getting all bitmaps I need to show in a list and I have the height and width of them all.

How is this library fill the gaps if there are any ? Does it make available items fit in a row same height  for all and adjust only the width ?

**Comment by JVillella** [comment]
In the library there is a `GreedoSpacingItemDecoration` that you can use to specify the spacing between items.

By how the algorithm works, the height is variable as well. The only constraint you can set is the **max** row height via `setMaxRowHeight(...)`. Hope that helps!

**Comment by AngleV** [comment]
@JVillella 
Yes i know about the new feature setAutoMeasureEnabled. However i got a small issue. if user flings i got some small jumps and i have spent days to figure out why but no luck :(

**Comment by JVillella** [comment]
I see. In terms of achieving that functionality with Greedo, if you abuse the AspectRatio, and the scale type of the ImageView, you may be able to pull something off.
